// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News.Api.Data;

namespace News.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("News.Api.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataDodania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = "20c3cbdc-3565-46a7-80d2-1dc30e5b9b36",
                            DataDodania = "20.03.2023",
                            Description = "This is a list of online newspaper archives and some magazines and journals, including both free and pay wall blocked digital archives. Most are scanned from microfilm into pdf, gif or similar graphic formats and many of the graphic archives have been indexed into searchable text dders.",
                            Title = "Wiadomości – program informacyjny"
                        },
                        new
                        {
                            Id = "6a3d9001-2181-4da0-8876-e65677d59a09",
                            DataDodania = "20.03.2023",
                            Description = "Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings f  in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field.Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field.Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field.Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field.Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field.",
                            Title = "This is a list of online newspaper archives"
                        },
                        new
                        {
                            Id = "5b6d993a-538e-42c5-9e19-a7c4f40ebf6e",
                            DataDodania = "20.03.2023",
                            Description = " s interested in the teachings from the field. Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field. Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field. Wayne State University in Detroit is now adding a bachelor’s in law for undergraduate students interested in the teachings from the field. ",
                            Title = "Archives and some magazines and journals"
                        },
                        new
                        {
                            Id = "7c5b95e3-8bf4-432b-8d2c-c62ae3ee43ce",
                            DataDodania = "20.03.2023",
                            Description = "Provost committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.Provost and Senior Vice President for Academic Affairs Mark Kornbluh told the committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.Provost and Senior Vice President for Academic Affairs Mark Kornbluh told the committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.",
                            Title = "Including both free and pay wall blocked digital"
                        },
                        new
                        {
                            Id = "880b07f6-96af-4b34-b318-751c8b6f1141",
                            DataDodania = "20.03.2023",
                            Description = "Provost  m that will provide students with a broad-based liberal arts degree.Provost and Senior Vice President for Academic Affairs Mark Kornbluh told the committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.Provost and Senior Vice President for Academic Affairs Mark Kornbluh told the committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.Provost and Senior Vice President for Academic Affairs Mark Kornbluh told the committee that the B.A. in law is designed to be an intradisciplinary program that will provide students with a broad-based liberal arts degree.",
                            Title = " Most are scanned from microfilm into pdf"
                        },
                        new
                        {
                            Id = "61f3467b-1edb-4d0e-b3b8-709379e7da95",
                            DataDodania = "20.03.2023",
                            Description = "Though  ture.Though the degree will not enable students to take the state bar exam and practice law, it will pave the way to law-adjoining careers or prepare students for a juris doctor in the future.Though the degree will not enable students to take the state bar exam and practice law, it will pave the way to law-adjoining careers or prepare students for a juris doctor in the future.",
                            Title = "Searchable text databases utilizing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
